# Home Work 01 
1. Numpy 
1. Pytorch (tensor (basic operations))

# DEADLINE

### IS-142 - 08.10.24 
### IS-141 - 15.10.24

## BLOKE №1 (numpy) 

1. Импортировать NumPy под именем np

In [2]:
import numpy as np

2. Создать вектор (одномерный массив) размера 20, заполненный нулями

In [3]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

3. Создать вектор размера 20, заполненный числом 1.75

In [4]:
np.full(20, 1.75)

array([1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75,
       1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75])

4. Создать вектор со значениями от 4 до 31

In [5]:
np.arange(4, 32)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

5. Развернуть вектор (первый становится последним)

In [6]:
np.arange(4, 32)[::-1]

array([31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4])

6. Создать матрицу (двумерный массив) 3x3 со значениями от 1 до 9

In [7]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

7. Создать 3x3 единичную матрицу

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Создать 4x4 пустую матрицу

In [9]:
np.empty((4, 4))

array([[4.68102143e-310, 0.00000000e+000, 2.41907520e-312,
        2.14321575e-312],
       [2.46151512e-312, 2.31297541e-312, 2.35541533e-312,
        2.05833592e-312],
       [2.22809558e-312, 2.56761491e-312, 2.48273508e-312,
        2.05833592e-312],
       [2.05833592e-312, 2.29175545e-312, 2.07955588e-312,
        2.14321575e-312]])

9. Создать единичную матрицу 4x4 со сдвигом на единицу вниз относительно главной диагонали

In [10]:
np.eye(4, 4, -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

10. Создать тензор 3x3x3 со случайными значениями

In [11]:
np.random.random((3,3,3))

array([[[0.53735082, 0.68543318, 0.00245568],
        [0.40691738, 0.40536851, 0.90406392],
        [0.8241363 , 0.02618323, 0.33742263]],

       [[0.82772999, 0.53850856, 0.4599951 ],
        [0.8250662 , 0.3347535 , 0.71268191],
        [0.35008716, 0.49799581, 0.38910342]],

       [[0.1796852 , 0.96854386, 0.1496829 ],
        [0.5242129 , 0.36359017, 0.79726154],
        [0.84152529, 0.05305993, 0.72253393]]])

11. Создать массив 5x5 со случайными значениями, найти минимум и максимум

In [12]:
a = np.random.random((5,5))
print(a)
print(a.min())
print(a.max())

[[0.98930073 0.44654678 0.14478857 0.18992627 0.85481985]
 [0.6426055  0.10225994 0.21423396 0.90192241 0.43597177]
 [0.47496619 0.00294228 0.61224265 0.89877488 0.56764521]
 [0.17255032 0.13961861 0.48413908 0.70703163 0.94065251]
 [0.21934024 0.91548858 0.53676644 0.13982387 0.18930124]]
0.0029422841964525936
0.9893007284921201


12. Создать случайный вектор размера 50 и найти среднее значение всех элементов

In [13]:
np.average(np.random.random(50))

0.5237588984884879

13. Создать матрицу с 0 внутри, и 1 на границах

In [14]:
np.array([[1,1,1,1],
          [1,0,0,1],
          [1,0,0,1],
          [1,1,1,1]])

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

14. Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [15]:
np.array([[0,0,0,0,0],
          [1,0,0,0,0],
          [0,2,0,0,0],
          [0,0,3,0,0],
          [0,0,0,4,0]])

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

15. Перемножить матрицы 5x3 и 3x2

In [16]:
np.arange(15).reshape(5,3).dot(np.arange(6).reshape(3,2))

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

16. Создать вектор состоящий из 15 элементов, поменять знак у элементов, значения которых между 6 и 12 

In [17]:
a = np.arange(15)
for i in a:
    if 6 < i < 12:
        a[i] = -i
a

array([  0,   1,   2,   3,   4,   5,   6,  -7,  -8,  -9, -10, -11,  12,
        13,  14])

17. Создать 2 матрицы A(3x3) и B(3x3), получить матрицу С путем поэлеметного умножения.

In [18]:
A = np.arange(9).reshape(3,3)
B = np.arange(1,10).reshape(3,3)
C = A * B
C

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

18. Найти максимальные и минимальные значения матрицы С по строкам и столбцам

In [59]:
print(C.max(axis=1))
print(C.max(axis=0))

[ 6 30 72]
[42 56 72]


19. Создать вектор со значениями от 0 до 1 c 10 наблюдениями

In [60]:
np.random.random(10)

array([0.60206432, 0.53729786, 0.38091693, 0.62588152, 0.82625745,
       0.88952141, 0.27076783, 0.69432771, 0.09136861, 0.06665866])

20. Отсортировать вектор

In [65]:
print(np.sort(np.random.random(10)))

[0.23432098 0.27679969 0.39350989 0.44594959 0.47677033 0.56962669
 0.6222     0.64938707 0.78614684 0.88994271]


21. Проверить, одинаковы ли 2 numpy массива

In [71]:
print((np.arange(10) == np.arange(10)).all())
print((np.arange(10) == np.arange(1, 11)).all())

True
False


22. Сделать массив неизменяемым

In [72]:
A = np.arange(10)
A.flags.writeable = False
A[0] = 10

ValueError: assignment destination is read-only

23. Создать случайный вектор из 20 элементов, найти квантиль от 10% и от 80%

In [76]:
A = np.random.random(20)
np.quantile(A, [0.1, 0.8])

array([0.07776826, 0.74730506])

24. Создать массив любой размерности состоящий из int и string

In [78]:
np.array([1, 2, "aboba"], dtype=object)

array([1, 2, 'aboba'], dtype=object)

25. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [97]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    print(f'{dtype} min = {np.iinfo(dtype).min}')
    print(f'{dtype} max = {np.iinfo(dtype).max}')
for dtype in [np.float16, np.float32, np.float64, np.float128]:
    print(f'{dtype} min = {np.finfo(dtype).min}')
    print(f'{dtype} max = {np.finfo(dtype).max}')


<class 'numpy.int8'> min = -128
<class 'numpy.int8'> max = 127
<class 'numpy.int16'> min = -32768
<class 'numpy.int16'> max = 32767
<class 'numpy.int32'> min = -2147483648
<class 'numpy.int32'> max = 2147483647
<class 'numpy.int64'> min = -9223372036854775808
<class 'numpy.int64'> max = 9223372036854775807
<class 'numpy.float16'> min = -65504.0
<class 'numpy.float16'> max = 65504.0
<class 'numpy.float32'> min = -3.4028234663852886e+38
<class 'numpy.float32'> max = 3.4028234663852886e+38
<class 'numpy.float64'> min = -1.7976931348623157e+308
<class 'numpy.float64'> max = 1.7976931348623157e+308
<class 'numpy.longdouble'> min = -inf
<class 'numpy.longdouble'> max = inf


26. Преобразовать массив из float в int

In [102]:
np.array([2.9, 3, 4]).astype(int)

array([2, 3, 4])

27. Отнять среднее из каждой строки в матрице

In [110]:
A = np.arange(9).reshape(3,3)
A = A - np.average(A)
A

array([[-4., -3., -2.],
       [-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

28. 

Дана данные из файла.

1,2,3,4,5

6,,,7,8

,,9,10,11

Необходимо прочитать его


In [127]:
str = "1,2,3,4,5\n6,,,7,8\n,,9,10,11"
data = [int(x) for x in str.replace('\n', ',').split(',') if x]
np.array(data)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

29. Посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [129]:
np.sum(np.arange(1, 10001) ** 2)

333383335000

## BLOKE №2 (tensors) 

1. Импортируйте pytorch

In [31]:
# Write your code

2. Создать вектор состящий из 10 элементов

In [32]:
# Write your code

3. Создать тензор из python list

In [33]:
# Write your code

4. Создать тензор из np.array

In [34]:
# Write your code

5. Создать тензор с нормальным распределением

In [35]:
# Write your code

6. Создать тензор размером 3х3х3

In [36]:
# Write your code

7. Создать единичную матрицу размером 4х5

In [37]:
# Write your code

8. Создать вектор размера 25, заполнить елементами со значениме pi

In [38]:
# Write your code

9. Умножить матрицу размера 9, заполненная от 0 до 8, поэлементно на любое число

In [39]:
# Write your code

10. Создать произвольный тензор с типом данных int8

In [40]:
# Write your code

11. Изменить тип данных из пункта 10 на int64

In [41]:
# Write your code

12. Создать случайный тензор размера 4x5 и найти среднее по 2му столбцу.

In [42]:
# Write your code

13. Создать пустой тензор произвольных размеров

In [43]:
# Write your code

14. Скалярно умножить 2 вектора

In [44]:
# Write your code

15. Умножить матрицу на вектор

In [45]:
# Write your code

16. Перемножить 2D матрицы 

In [46]:
# Write your code

17. Перемножить 3D тензоры

In [47]:
# Write your code

18. Создать вектор с нормальным распределением и вывести элементы больше 0.5

In [48]:
# Write your code

19. Создать матрицу 3х3 заполненную единицами и заменить 1й столбец на 4

In [49]:
# Write your code

20. Создать матрицу и вывести сумму по каждой строке

In [50]:
# Write your code

20. Создать матрицу и вывести среднее по каждому столбцу

In [51]:
# Write your code

21. Создать 2 вектора и сконкатенировать по 1 оси

In [52]:
# Write your code

22. Перемножим две большие единичные матрицы. 
Сначал на центральном процессоре, затем попробуйте на GPU

In [53]:
# Write your code