# Home Work 01 
1. Numpy 
1. Pytorch (tensor (basic operations))

# DEADLINE

### IS-142 - 08.10.24 
### IS-141 - 15.10.24

## BLOKE №1 (numpy) 

1. Импортировать NumPy под именем np

In [1]:
import numpy as np

2. Создать вектор (одномерный массив) размера 20, заполненный нулями

In [50]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

3. Создать вектор размера 20, заполненный числом 1.75

In [49]:
np.full(20, 1.75)

array([1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75,
       1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75])

4. Создать вектор со значениями от 4 до 31

In [ ]:
np.arange(4, 32)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

5. Развернуть вектор (первый становится последним)

In [48]:
np.arange(4, 32)[::-1]

array([31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4])

6. Создать матрицу (двумерный массив) 3x3 со значениями от 1 до 9

In [47]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

7. Создать 3x3 единичную матрицу

In [46]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Создать 4x4 пустую матрицу

In [45]:
np.empty((4, 4))

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

9. Создать единичную матрицу 4x4 со сдвигом на единицу вниз относительно главной диагонали

In [44]:
np.eye(4, 4, -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

10. Создать тензор 3x3x3 со случайными значениями

In [43]:
np.random.random((3,3,3))

array([[[0.04747914, 0.67877869, 0.74889831],
        [0.91067744, 0.05269437, 0.79062627],
        [0.25635661, 0.65970173, 0.74269349]],

       [[0.81351599, 0.93020934, 0.9203335 ],
        [0.38022471, 0.53605342, 0.41446709],
        [0.12734246, 0.36818511, 0.61415801]],

       [[0.57791023, 0.22752986, 0.27100072],
        [0.68492237, 0.23499931, 0.06777265],
        [0.77044408, 0.00263055, 0.4586231 ]]])

11. Создать массив 5x5 со случайными значениями, найти минимум и максимум

In [56]:
a = np.random.random((5,5))
print(a)
print(a.min())
print(a.max())

[[0.07412779 0.69584126 0.87296279 0.99112109 0.39458314]
 [0.93045178 0.83848957 0.10003811 0.43092494 0.88083143]
 [0.03213951 0.94533904 0.03198252 0.32575314 0.17609069]
 [0.97679982 0.48126008 0.53253648 0.03402453 0.70508892]
 [0.14312637 0.91943961 0.03014438 0.86531225 0.77161602]]
0.030144376754296598
0.9911210922640503


12. Создать случайный вектор размера 50 и найти среднее значение всех элементов

In [59]:
np.average(np.random.random(50))

0.5199127647639393

13. Создать матрицу с 0 внутри, и 1 на границах

In [71]:
np.array([[1,1,1,1],
          [1,0,0,1],
          [1,0,0,1],
          [1,1,1,1]])

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

14. Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [72]:
np.array([[0,0,0,0,0],
          [1,0,0,0,0],
          [0,2,0,0,0],
          [0,0,3,0,0],
          [0,0,0,4,0]])

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

15. Перемножить матрицы 5x3 и 3x2

In [75]:
np.arange(15).reshape(5,3).dot(np.arange(6).reshape(3,2))

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

16. Создать вектор состоящий из 15 элементов, поменять знак у элементов, значения которых между 6 и 12 

In [84]:
a = np.arange(15)
for i in a:
    if 6 < i < 12:
        a[i] = -i
a

array([  0,   1,   2,   3,   4,   5,   6,  -7,  -8,  -9, -10, -11,  12,
        13,  14])

17. Создать 2 матрицы A(3x3) и B(3x3), получить матрицу С путем поэлеметного умножения.

In [86]:
A = np.arange(9).reshape(3,3)
B = np.arange(1,10).reshape(3,3)
C = A * B
C

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

18. Найти максимальные и минимальные значения матрицы С по строкам и столбцам

In [ ]:
# Write your code

19. Создать вектор со значениями от 0 до 1 c 10 наблюдениями

In [21]:
# Write your code

20. Отсортировать вектор

In [ ]:
# Write your code

21. Проверить, одинаковы ли 2 numpy массива

In [ ]:
# Write your code

22. Сделать массив неизменяемым

In [ ]:
# Write your code

23. Создать случайный вектор из 20 элементов, найти квантиль от 10% и от 80%

In [ ]:
# Write your code

24. Создать массив любой размерности состоящий из int и string

In [ ]:
# Write your code

25. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [22]:
# Write your code

26. Преобразовать массив из float в int

In [ ]:
# Write your code

27. Отнять среднее из каждой строки в матрице

In [23]:
# Write your code

28. 

Дана данные из файла.

1,2,3,4,5

6,,,7,8

,,9,10,11

Необходимо прочитать его


In [ ]:
# Write your code

29. Посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [ ]:
# Write your code

## BLOKE №2 (tensors) 

1. Импортируйте pytorch

In [ ]:
# Write your code

2. Создать вектор состящий из 10 элементов

In [ ]:
# Write your code

3. Создать тензор из python list

In [ ]:
# Write your code

4. Создать тензор из np.array

In [ ]:
# Write your code

5. Создать тензор с нормальным распределением

In [ ]:
# Write your code

6. Создать тензор размером 3х3х3

In [ ]:
# Write your code

7. Создать единичную матрицу размером 4х5

In [ ]:
# Write your code

8. Создать вектор размера 25, заполнить елементами со значениме pi

In [ ]:
# Write your code

9. Умножить матрицу размера 9, заполненная от 0 до 8, поэлементно на любое число

In [ ]:
# Write your code

10. Создать произвольный тензор с типом данных int8

In [ ]:
# Write your code

11. Изменить тип данных из пункта 10 на int64

In [ ]:
# Write your code

12. Создать случайный тензор размера 4x5 и найти среднее по 2му столбцу.

In [ ]:
# Write your code

13. Создать пустой тензор произвольных размеров

In [ ]:
# Write your code

14. Скалярно умножить 2 вектора

In [ ]:
# Write your code

15. Умножить матрицу на вектор

In [ ]:
# Write your code

16. Перемножить 2D матрицы 

In [ ]:
# Write your code

17. Перемножить 3D тензоры

In [ ]:
# Write your code

18. Создать вектор с нормальным распределением и вывести элементы больше 0.5

In [ ]:
# Write your code

19. Создать матрицу 3х3 заполненную единицами и заменить 1й столбец на 4

In [ ]:
# Write your code

20. Создать матрицу и вывести сумму по каждой строке

In [ ]:
# Write your code

20. Создать матрицу и вывести среднее по каждому столбцу

In [ ]:
# Write your code

21. Создать 2 вектора и сконкатенировать по 1 оси

In [ ]:
# Write your code

22. Перемножим две большие единичные матрицы. 
Сначал на центральном процессоре, затем попробуйте на GPU

In [ ]:
# Write your code