# Home Work 01 
1. Numpy 
1. Pytorch (tensor (basic operations))

# DEADLINE

### IS-142 - 08.10.24 
### IS-141 - 15.10.24

## BLOKE №1 (numpy) 

1. Импортировать NumPy под именем np

In [9]:
import numpy as np

2. Создать вектор (одномерный массив) размера 20, заполненный нулями

In [10]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

3. Создать вектор размера 20, заполненный числом 1.75

In [11]:
np.full(20, 1.75)

array([1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75,
       1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75])

4. Создать вектор со значениями от 4 до 31

In [12]:
np.arange(4, 32)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

5. Развернуть вектор (первый становится последним)

In [13]:
np.arange(4, 32)[::-1]

array([31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4])

6. Создать матрицу (двумерный массив) 3x3 со значениями от 1 до 9

In [14]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

7. Создать 3x3 единичную матрицу

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Создать 4x4 пустую матрицу

In [16]:
np.empty((4, 4))

array([[4.65022983e-310, 0.00000000e+000, 2.41907520e-312,
        2.14321575e-312],
       [2.46151512e-312, 2.31297541e-312, 2.35541533e-312,
        2.05833592e-312],
       [2.22809558e-312, 2.56761491e-312, 2.48273508e-312,
        2.05833592e-312],
       [2.05833592e-312, 2.29175545e-312, 2.07955588e-312,
        2.14321575e-312]])

9. Создать единичную матрицу 4x4 со сдвигом на единицу вниз относительно главной диагонали

In [17]:
np.eye(4, 4, -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

10. Создать тензор 3x3x3 со случайными значениями

In [18]:
np.random.random((3,3,3))

array([[[0.49783463, 0.78829607, 0.86098638],
        [0.01878032, 0.92393349, 0.87946983],
        [0.17156151, 0.53453398, 0.10814293]],

       [[0.56996333, 0.14663562, 0.19952268],
        [0.53906224, 0.1639049 , 0.1009549 ],
        [0.99678426, 0.60430947, 0.81085013]],

       [[0.84628807, 0.54060367, 0.83039879],
        [0.52515296, 0.4170372 , 0.27701724],
        [0.93875558, 0.71011317, 0.13555043]]])

11. Создать массив 5x5 со случайными значениями, найти минимум и максимум

In [19]:
a = np.random.random((5,5))
print(a)
print(a.min())
print(a.max())

[[0.08634666 0.20536254 0.5499626  0.37530985 0.43219047]
 [0.78277148 0.82403153 0.01745005 0.22804413 0.80943022]
 [0.22368794 0.61843768 0.02898419 0.3060914  0.05771518]
 [0.62035438 0.84932142 0.92207924 0.18688226 0.09056424]
 [0.3609419  0.30096979 0.24406134 0.14042719 0.04421339]]
0.017450047984879924
0.92207923834525


12. Создать случайный вектор размера 50 и найти среднее значение всех элементов

In [20]:
np.average(np.random.random(50))

np.float64(0.4990764444534902)

13. Создать матрицу с 0 внутри, и 1 на границах

In [21]:
np.array([[1,1,1,1],
          [1,0,0,1],
          [1,0,0,1],
          [1,1,1,1]])

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

14. Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [22]:
np.array([[0,0,0,0,0],
          [1,0,0,0,0],
          [0,2,0,0,0],
          [0,0,3,0,0],
          [0,0,0,4,0]])

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

15. Перемножить матрицы 5x3 и 3x2

In [23]:
np.arange(15).reshape(5,3).dot(np.arange(6).reshape(3,2))

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

16. Создать вектор состоящий из 15 элементов, поменять знак у элементов, значения которых между 6 и 12 

In [24]:
a = np.arange(15)
for i in a:
    if 6 < i < 12:
        a[i] = -i
a

array([  0,   1,   2,   3,   4,   5,   6,  -7,  -8,  -9, -10, -11,  12,
        13,  14])

17. Создать 2 матрицы A(3x3) и B(3x3), получить матрицу С путем поэлеметного умножения.

In [25]:
A = np.arange(9).reshape(3,3)
B = np.arange(1,10).reshape(3,3)
C = A * B
C

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

18. Найти максимальные и минимальные значения матрицы С по строкам и столбцам

In [26]:
print(C.max(axis=1))
print(C.max(axis=0))

[ 6 30 72]
[42 56 72]


19. Создать вектор со значениями от 0 до 1 c 10 наблюдениями

In [27]:
np.random.random(10)

array([0.54179739, 0.86860842, 0.67923787, 0.04698759, 0.13811281,
       0.17506066, 0.41809074, 0.26919167, 0.72392585, 0.95840708])

20. Отсортировать вектор

In [28]:
print(np.sort(np.random.random(10)))

[0.12788151 0.22576367 0.34622672 0.39865988 0.47310612 0.55443853
 0.56718188 0.57528995 0.64620871 0.99551902]


21. Проверить, одинаковы ли 2 numpy массива

In [29]:
print((np.arange(10) == np.arange(10)).all())
print((np.arange(10) == np.arange(1, 11)).all())

True
False


22. Сделать массив неизменяемым

In [30]:
A = np.arange(10)
A.flags.writeable = False
A[0] = 10

ValueError: assignment destination is read-only

23. Создать случайный вектор из 20 элементов, найти квантиль от 10% и от 80%

In [ ]:
A = np.random.random(20)
np.quantile(A, [0.1, 0.8])

array([0.07776826, 0.74730506])

24. Создать массив любой размерности состоящий из int и string

In [ ]:
np.array([1, 2, "aboba"], dtype=object)

array([1, 2, 'aboba'], dtype=object)

25. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [ ]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    print(f'{dtype} min = {np.iinfo(dtype).min}')
    print(f'{dtype} max = {np.iinfo(dtype).max}')
for dtype in [np.float16, np.float32, np.float64, np.float128]:
    print(f'{dtype} min = {np.finfo(dtype).min}')
    print(f'{dtype} max = {np.finfo(dtype).max}')


<class 'numpy.int8'> min = -128
<class 'numpy.int8'> max = 127
<class 'numpy.int16'> min = -32768
<class 'numpy.int16'> max = 32767
<class 'numpy.int32'> min = -2147483648
<class 'numpy.int32'> max = 2147483647
<class 'numpy.int64'> min = -9223372036854775808
<class 'numpy.int64'> max = 9223372036854775807
<class 'numpy.float16'> min = -65504.0
<class 'numpy.float16'> max = 65504.0
<class 'numpy.float32'> min = -3.4028234663852886e+38
<class 'numpy.float32'> max = 3.4028234663852886e+38
<class 'numpy.float64'> min = -1.7976931348623157e+308
<class 'numpy.float64'> max = 1.7976931348623157e+308
<class 'numpy.longdouble'> min = -inf
<class 'numpy.longdouble'> max = inf


26. Преобразовать массив из float в int

In [ ]:
np.array([2.9, 3, 4]).astype(int)

array([2, 3, 4])

27. Отнять среднее из каждой строки в матрице

In [ ]:
A = np.arange(9).reshape(3,3)
A = A - np.average(A)
A

array([[-4., -3., -2.],
       [-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

28. 

Дана данные из файла.

1,2,3,4,5

6,,,7,8

,,9,10,11

Необходимо прочитать его


In [ ]:
str = "1,2,3,4,5\n6,,,7,8\n,,9,10,11"
data = [int(x) for x in str.replace('\n', ',').split(',') if x]
np.array(data)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

29. Посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [ ]:
np.sum(np.arange(1, 10001) ** 2)

333383335000

## BLOKE №2 (tensors) 

1. Импортируйте pytorch

In [1]:
import torch

2. Создать вектор состящий из 10 элементов

In [ ]:
torch.empty(10)

tensor([9.5135e-09, 3.0715e-41, 1.0761e+25, 4.5845e-41, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00])

3. Создать тензор из python list

In [ ]:
torch.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

4. Создать тензор из np.array

In [39]:
torch.tensor(np.array([1,2,3,4,5]))

tensor([1, 2, 3, 4, 5])

5. Создать тензор с нормальным распределением

In [38]:
torch.randn(3,3)

tensor([[ 0.5203, -1.5606,  2.0208],
        [-1.0596,  0.1645,  0.1731],
        [ 0.4731, -1.3852,  0.0061]])

6. Создать тензор размером 3х3х3

In [40]:
torch.empty([3,3,3])

tensor([[[4.9670e+26, 4.5845e-41, 4.9670e+26],
         [4.5845e-41, 7.3403e-08, 3.0715e-41],
         [6.1750e-08, 3.0715e-41, 0.0000e+00]],

        [[0.0000e+00, 7.5790e-08, 3.0715e-41],
         [9.5135e-09, 3.0715e-41, 1.5420e-37],
         [4.5845e-41, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])

7. Создать единичную матрицу размером 4х5

In [41]:
torch.eye(4,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

8. Создать вектор размера 25, заполнить елементами со значениме pi

In [44]:
torch.full([25],np.pi)

tensor([3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
        3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
        3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416])

9. Умножить матрицу размера 9, заполненная от 0 до 8, поэлементно на любое число

In [48]:
torch.arange(9).reshape(3,3) * 3

tensor([[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]])

10. Создать произвольный тензор с типом данных int8

In [51]:
a = torch.arange(10, dtype=torch.int8)

11. Изменить тип данных из пункта 10 на int64

In [ ]:
a = a.to(torch.int64)
a.dtype

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

12. Создать случайный тензор размера 4x5 и найти среднее по 2му столбцу.

In [86]:
torch.mean(torch.randn(4,5), dim=0)[1]

tensor(-0.4267)

13. Создать пустой тензор произвольных размеров

In [118]:
torch.empty(np.random.randint(10) + 1, np.random.randint(10) + 1)

tensor([[1.1627e-10, 3.0715e-41, 6.1752e-08, 3.0715e-41, 1.1210e-43, 0.0000e+00],
        [8.9683e-44, 0.0000e+00, 7.1639e+25, 3.0708e-41, 8.9683e-44, 0.0000e+00],
        [7.1639e+25, 3.0708e-41, 7.9967e+20, 1.2801e-11, 8.3378e-10, 8.2734e+20],
        [3.2691e+21, 3.1062e-18, 0.0000e+00, 0.0000e+00, 1.1351e-43, 0.0000e+00]])

14. Скалярно умножить 2 вектора

In [121]:
a = torch.tensor([1,2,3])
b = torch.tensor([1,2,3])
torch.dot(a,b)

tensor(14)

15. Умножить матрицу на вектор

In [128]:
torch.tensor([[1,2,3],[1,2,3]]) @ torch.tensor([1,2,3])

tensor([14, 14])

16. Перемножить 2D матрицы 

In [130]:
torch.tensor([[1,2,3],[1,2,3]]) @ torch.tensor([[1,2,3],[1,2,3]]).T

tensor([[14, 14],
        [14, 14]])

17. Перемножить 3D тензоры

In [133]:
torch.arange(27).reshape(3,3,3) @ torch.arange(27).reshape(3,3,3)

tensor([[[  15,   18,   21],
         [  42,   54,   66],
         [  69,   90,  111]],

        [[ 366,  396,  426],
         [ 474,  513,  552],
         [ 582,  630,  678]],

        [[1203, 1260, 1317],
         [1392, 1458, 1524],
         [1581, 1656, 1731]]])

18. Создать вектор с нормальным распределением и вывести элементы больше 0.5

In [158]:
a = torch.randn(100)
a[a > 0.5]

tensor([0.8707, 1.4644, 1.6918, 0.7466, 0.5160, 0.8108, 1.2972, 0.8377, 0.9362,
        1.6072, 1.1904, 1.4730, 1.2527, 2.1656, 0.9308, 0.5874, 1.3640, 0.7539,
        0.8572, 0.9540, 0.9935, 1.7106, 0.6540, 0.7508, 1.0031, 1.3974, 0.9645,
        1.1574, 1.7535])

19. Создать матрицу 3х3 заполненную единицами и заменить 1й столбец на 4

In [183]:
a = torch.full([3,3],1)
a[:,0] = 4
a

tensor([[4, 1, 1],
        [4, 1, 1],
        [4, 1, 1]])

20. Создать матрицу и вывести сумму по каждой строке

In [ ]:
a = torch.arange(9).reshape(3,3)
print(torch.sum(a[0]))
print(torch.sum(a[1]))
print(torch.sum(a[2]))


tensor([0, 3, 6])
tensor(3)
tensor(12)
tensor(21)


20. Создать матрицу и вывести среднее по каждому столбцу

In [196]:
a = torch.randn(3,3)
print(torch.mean(a[:,0]))
print(torch.mean(a[:,1]))
print(torch.mean(a[:,2]))


tensor(-0.0990)
tensor(-0.0069)
tensor(-0.0205)


21. Создать 2 вектора и сконкатенировать по 1 оси

In [204]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
torch.concat([a,b])

tensor([1, 2, 3, 4, 5, 6])

22. Перемножим две большие единичные матрицы. 
Сначал на центральном процессоре, затем попробуйте на GPU

In [5]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

n = 15000
a = torch.eye(n,n)
b = torch.eye(n,n)
a @ b


Using device: cuda


tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])